spring:
  application:
    name: jan-2024-java-spring
  datasource:
    url: "jdbc:mysql://localhost:3306/jan_2024_spring?createDatabaseIfNotExist=true"
    username: "root"
    password: "root"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update